#!/bin/bash
sudo apt update
sudo apt upgrade

# get homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# set up the dotfiles
sudo apt install -y pipx
pipx install mackup 1> /dev/null

cp -i ~/dotfiles/.mackup.cfg ~/.mackup.cfg
mackup restore

